//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigMansStuff.PracticeSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAudioFolder {
            get {
                return ((string)(this["LastAudioFolder"]));
            }
            set {
                this["LastAudioFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFilename {
            get {
                return ((string)(this["LastFilename"]));
            }
            set {
                this["LastFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SupressVersionCheck {
            get {
                return ((bool)(this["SupressVersionCheck"]));
            }
            set {
                this["SupressVersionCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastFilterIndex {
            get {
                return ((int)(this["LastFilterIndex"]));
            }
            set {
                this["LastFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int Latency {
            get {
                return ((int)(this["Latency"]));
            }
            set {
                this["Latency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/18/2010 12:00:00")]
        public global::System.DateTime LastVersionCheckDateTime {
            get {
                return ((global::System.DateTime)(this["LastVersionCheckDateTime"]));
            }
            set {
                this["LastVersionCheckDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SoundTouch_USE_AA_FILTER {
            get {
                return ((int)(this["SoundTouch_USE_AA_FILTER"]));
            }
            set {
                this["SoundTouch_USE_AA_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int SoundTouch_AA_FILTER_LENGTH {
            get {
                return ((int)(this["SoundTouch_AA_FILTER_LENGTH"]));
            }
            set {
                this["SoundTouch_AA_FILTER_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SoundTouch_SEQUENCE_MS {
            get {
                return ((int)(this["SoundTouch_SEQUENCE_MS"]));
            }
            set {
                this["SoundTouch_SEQUENCE_MS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SoundTouch_SEEKWINDOW_MS {
            get {
                return ((int)(this["SoundTouch_SEEKWINDOW_MS"]));
            }
            set {
                this["SoundTouch_SEEKWINDOW_MS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SoundTouch_OVERLAP_MS {
            get {
                return ((int)(this["SoundTouch_OVERLAP_MS"]));
            }
            set {
                this["SoundTouch_OVERLAP_MS"] = value;
            }
        }
    }
}
